# Indica la imagen base que vamos a usar, como base de la imagen
# Todas las imagenes empiezan de un from
FROM ubuntu

# Que ejecute a tiempo de construcción
RUN touch /usr/src/hola-platzi
RUN rm /usr/src/hola-platzi