# Idica que debería soportar docker compose para construir la aplicacion
version: "3.8"

# Aca se habla de servicios y no de contenedores
# Son parte de la totalidad de la aplicacion
# Un servicio puede contener mas de un contenedor
services:
  app:
    # Utilizando una imagen predefinida
    image: platziapp
    environment:
      # Agregando la variable de entorno al contenedor
      MONGO_URL: "mongodb://db:27017/test"
    # Dependencias del servicio de otro servicio
    # Garantiza que el servicio este cargado pero no controla el tiempo de inicio de su dependencia
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mongo
