apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver
  labels:
    app: contmagic
    # Enviroment
    env: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contmagic
      env: staging
  template:
    metadata:
      labels:
        app: contmagic
        env: staging
    spec:
      containers:
      - name: nginx
        image: nginx
